CXX = g++
CXXFLAGS = -std=c++11 -O3 -I/usr/include/eigen3
k-means:         common.o
compLearn:       common.o
modPerceptron:   common.o
classify:        common.o
spK-means:       commonDoc.o
spCompLearn:     commonDoc.o
sdK-means:       commonDoc.o
sdCompLearn:     commonDoc.o
evalClustering:  commonDoc.o
KLnmfLbl:        commonDoc.o
k-means++:       common.o
PLSALbl:         commonDoc.o
evalClustering2: commonDoc.o
